apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: norway-map-ingress
  labels:
    name: norway-map-ingress
spec:
  rules:
    - host: nmk.michaltorma.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: norway-map-service
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: norway-map-service
spec:
  selector:
    app: norway-map
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: norway-map
spec:
  selector:
    matchLabels:
      app: norway-map
  template:
    metadata:
      labels:
        app: norway-map
    spec:
      containers:
        - name: norway-map
          image: registry.michaltorma.com/norway-map:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
